tf2-automatic/tf2-automatic

apps/bot/src/tf2/tf2.service.ts

The item schema is not used for anything in the bot

fix(bot): stop fetching item schema

---

apps/bot-manager/src/common/utils/backoff-strategy.ts
apps/bot-manager/src/common/utils/default-job-options.ts
apps/bot-manager/src/inventories/interfaces/queue.interfaces.ts
apps/bot-manager/src/inventories/inventories.controller.ts
apps/bot-manager/src/inventories/inventories.module.ts
apps/bot-manager/src/inventories/inventories.processor.ts
apps/bot-manager/src/inventories/inventories.service.ts
apps/bot-manager/src/trades/interfaces/trade-queue.interface.ts
apps/bot-manager/src/trades/processors/trades.processor.ts
apps/bot-manager/src/trades/trades.module.ts
libs/bot-manager-data/src/index.ts
libs/bot-manager-data/src/lib/inventories.ts
libs/bot-manager-data/src/lib/misc.ts
libs/bot-manager-data/src/lib/trades.ts
libs/dto/src/index.ts
libs/dto/src/lib/inventories.ts
libs/dto/src/lib/misc.ts
libs/dto/src/lib/trades.ts

Instead of getting the inventory from the bot if it is not in the cache, you instead add the
inventory to the queue and it will eventually be loaded depending on the configured retry options.
BREAKING CHANGE: In order to load an inventory, you need to add it to the queue and wait for it to
be fetched.

feat(bot-manager): inventory queue

---

apps/bot/src/events/events.service.ts
apps/bot/src/trades/trades.service.ts
libs/bot-data/src/lib/trades.ts

An event will now be published when an offer is accepted or sent and needs to be confirmed
Fixes #250

feat(bot): confirmation needed event

---

apps/bot-manager/src/inventories/inventories.service.ts
apps/bot-manager/src/trades/trades.service.ts

If an offer is canceled but has a tradeID, then the offer was previously accepted and the items are moved back.
BREAKING CHANGE: Renamed RabbitMQ queue "bot-manager.add-inventory-items" to "bot-manager.update-inventory-items"

feat(bot-manager): handle trade rollbacks

---

apps/bot/src/trades/trades.service.ts
libs/bot-data/src/lib/trades.ts

`TRADE_CONFIRMATION_NEEDED_EVENT` was inconsistent with the rest of the trade offer events. The types provided for the rest were incorrect.

fix incorrect and inconsistent offer event types

---

apps/bot-manager/src/inventories/inventories.service.ts
libs/bot-manager-data/src/lib/inventories.ts

Keep track of items gained using TF2 events
BREAKING CHANGE: Inventory items can be partial and only consist of an appid, contextid and assetid
Fix #284

feat(bot-manager): add partial item to inventory on tf2 event

---

apps/bot/src/bot/bot.service.ts
apps/bot/src/profile/profile.controller.ts
apps/bot/src/profile/profile.module.ts
apps/bot/src/profile/profile.service.ts
apps/bot/src/tf2/tf2.module.ts
apps/bot/src/tf2/tf2.service.ts
libs/bot-data/src/lib/profile.ts
libs/dto/src/lib/profile.ts

Set the bots custom game (alongside TF2) through API
Includes `PUT /profile/game` with body:
```json
{
"name": "Super cool game!"
}
```
And `DELETE /profile/game` to go back to playing TF2 only
Setting the name to an empty string will have the same effect as calling the DELETE API
Using PUT to be consistent with the other profile APIs

feat(bot): play custom game

---

apps/bptf-manager/src/listings/classes/desired-listing.class.ts
apps/bptf-manager/src/listings/desired-listings.service.spec.ts
apps/bptf-manager/src/listings/desired-listings.service.ts
apps/bptf-manager/src/listings/listeners/desired-listings.listener.spec.ts
apps/bptf-manager/src/listings/listeners/desired-listings.listener.ts
apps/bptf-manager/src/listings/listings.module.ts
libs/testing/.eslintrc.json
libs/testing/README.md
libs/testing/jest.config.ts
libs/testing/project.json
libs/testing/src/index.ts
libs/testing/src/mocks/index.ts
libs/testing/src/mocks/redis.mock.ts
libs/testing/src/mocks/redlock.mock.spec.ts
libs/testing/src/mocks/redlock.mock.ts
libs/testing/tsconfig.json
libs/testing/tsconfig.lib.json
libs/testing/tsconfig.spec.json
package.json
pnpm-lock.yaml
tsconfig.base.json

Move listeners to seperate service to make the methods public so that it is easier to test and won't clutter the DesiredListingsService with methods that should not be called. Could also move the listener service into a seperate module so that it can't be imported at all but it is not that important.

refactor(bptf-manager): refactor and test desired listings

---

apps/bot/src/bot/bot.service.ts
apps/bot/src/common/config/configuration.ts
apps/bot/src/common/config/validation.ts
apps/bot/src/trades/trades.service.ts
patches/@types__steam-tradeoffer-manager@2.11.0.patch
pnpm-lock.yaml

API keys may not be available on the apikey dev page anymore.

feat(bot): manually set Steam API key

---

apps/bot/README.md
apps/bot/src/app.module.ts
apps/bot/src/common/config/configuration.ts
apps/bot/src/common/config/validation.ts
apps/bot/src/events/custom/custom.interface.ts
apps/bot/src/events/custom/rabbitmq-events.service.ts
apps/bot/src/events/custom/redis-events.service.ts
apps/bot/src/events/events.module.ts
apps/bot/src/events/events.service.ts
apps/bot/src/main.ts
examples/bot-data-usage/main.ts
examples/minimum-setup/docker-compose.yml
examples/rabbitmq/README.md
examples/recommended-setup/docker-compose.yml
examples/redis/.npmrc
examples/redis/README.md
examples/redis/no-persist.ts
examples/redis/package.json
examples/redis/persist.ts

The bot can now publish events to Redis or RabbitMQ
BREAKING CHANGE: New environment variables for choosing how to publish events

feat(bot): publish events to redis or rabbitmq

---

libs/is-refined-validator/.eslintrc.json
libs/is-refined-validator/package.json
libs/is-refined-validator/project.json
libs/is-steamid-validator/.eslintrc.json
libs/is-steamid-validator/package.json
libs/is-steamid-validator/project.json
tsconfig.base.json

Publish refined and steamid validators. This also fixes an issue with missing dependencies for the bptf-manager-data library.

feat: publish validators

---

.eslintrc.json
libs/bptf-manager-data/project.json

Use deprecated "external" build option for bptf-manager-data.

fix(bptf-manager-data): missing dependencies

---

apps/bot-manager/src/app.module.ts
apps/bot-manager/src/escrow/escrow.service.ts
apps/bot-manager/src/heartbeats/heartbeats.service.ts
apps/bot-manager/src/inventories/inventories.service.ts
apps/bptf-manager/src/app.module.ts
apps/bptf-manager/src/inventories/inventories.service.ts
apps/bptf-manager/src/listings/current-listings.service.ts
apps/bptf-manager/src/listings/desired-listings.service.spec.ts
apps/bptf-manager/src/listings/desired-listings.service.ts
apps/bptf-manager/src/listings/listeners/desired-listings.listener.spec.ts
apps/bptf-manager/src/listings/listing-limits.service.ts
apps/bptf-manager/src/listings/manage-listings.service.ts
apps/bptf-manager/src/notifications/notifications.service.ts
apps/bptf-manager/src/tokens/tokens.service.ts
libs/config/src/connections/redis.ts
libs/config/src/events.ts
libs/locking/src/lib/locking.ts

Redis keys were not prefixed properly
BREAKING CHANGE: Because the keys have changed all existing data in redis will no longer be used

fix: correct redis key prefixes

---

libs/is-refined-validator/project.json
libs/is-steamid-validator/project.json

I don't remember why they were in the first place.

chore: don't publish validators to npm

---

libs/nestjs/src/lib/interceptors/idempotency.interceptor.ts

It should cache everything but status code 5xx

fix: correct error status check for idempotency interceptor

---

libs/tf2-format/src/lib/parsing/econ/parser.spec.ts
libs/tf2-format/src/lib/parsing/econ/parser.ts
libs/tf2-format/src/lib/parsing/econ/test-data.ts

Spells on unusuals were ignored when the item was a cosmetic
Fix #616

fix(tf2-format): fix problem with parsing spelled unusuals

---

libs/tf2-format/src/lib/parsing/econ/parser.spec.ts
libs/tf2-format/src/lib/parsing/econ/parser.ts
libs/tf2-format/src/lib/parsing/econ/test-data.ts

The item does not have a rarity tag so it is not detecting the statclock. Also added a check to force the item to be Strange.
Fix #619

fix(tf2-format): handle edge case with applied war paints on strange items

---

.github/workflows/ci.yml
.github/workflows/release.yml

It is a waste of time to write the same data multiple times.

ci: only write to pnpm cache in affected jobs

---

.github/workflows/release.yml

This should fix the "failure" GitHub makes even though everything passes.

ci: skip publish jobs if there is nothing to publish

---

libs/tf2-format/src/lib/sku/sku.spec.ts
libs/tf2-format/src/lib/sku/sku.ts
libs/tf2-format/src/lib/sku/test-data.ts

The item-to-SKU parser will read a paintkit ID of 0 as a falsey value, resulting in Red Rock Roscoe skins not having a paintkit in their SKU.

fix(tf2-format): check if attribute is a number before adding it to the sku
