package-lock.json
package.json

There is a weird merge conflict

chore(deps): downgrade swagger

---

apps/bot/src/bot/bot.service.ts

refactor(bot): move poll interval reconnect logic

---

apps/bot-manager/src/inventories/interfaces/queue.interfaces.ts
apps/bot-manager/src/inventories/inventories.processor.ts
apps/bot-manager/src/inventories/inventories.service.ts
libs/dto/src/lib/inventories.ts

feat(bot-manager): set inventory cache ttl

---

docs/events.md

docs: correct event typos

---

apps/bot/src/common/config/configuration.ts
apps/bot/src/common/config/validation.ts
apps/bot/src/manager/manager.service.ts

feat(bot): configure heartbeat interval

---

apps/bot-manager/src/heartbeats/heartbeats.module.ts
apps/bot-manager/src/heartbeats/heartbeats.processor.ts
apps/bot-manager/src/heartbeats/heartbeats.service.ts
apps/bot-manager/src/heartbeats/interfaces/queue.interface.ts
libs/bot-manager-data/src/lib/heartbeats.ts
package-lock.json
package.json

Create job when heartbeat is made to check if a new heartbeat is made after the given interval
Fix #240

feat(bot-manager): delete bot if no heartbeat is made

---

apps/bot-manager/src/inventories/interfaces/queue.interfaces.ts
apps/bot-manager/src/inventories/inventories.processor.ts
apps/bot-manager/src/inventories/inventories.service.ts
apps/bot/src/inventories/inventories.controller.ts
apps/bot/src/inventories/inventories.service.ts
libs/bot-manager-data/src/lib/inventories.ts
libs/dto/src/lib/inventories.ts

Add option to request non-tradable items for inventory loading

---

apps/bot-manager/src/inventories/inventories.service.ts
libs/bot-manager-data/src/lib/inventories.ts

When a cached inventory is updated a message will be published with the gained and lost items

feat(bot-manager): inventory change events

---

apps/bot/src/trades/trades.service.ts

Bot was not publishing confirmation needed event when sending offers

fix(bot): publish confirmation event for sent offer

---

apps/bptf-manager/src/main.ts
package-lock.json
package.json

feat(bptf-manager): increase max payload size

---

apps/bptf-manager/src/app.module.ts
apps/bptf-manager/src/notifications/interfaces/notifications.ts
apps/bptf-manager/src/notifications/interfaces/queue.ts
apps/bptf-manager/src/notifications/notifications.controller.ts
apps/bptf-manager/src/notifications/notifications.module.ts
apps/bptf-manager/src/notifications/notifications.processor.ts
apps/bptf-manager/src/notifications/notifications.service.ts
libs/bptf-manager-data/src/index.ts
libs/bptf-manager-data/src/lib/notifications.ts

Fetches all notifications when an agent has been registered

feat(bptf-manager): get notifications

---

apps/bot/src/bot/bot.service.ts
apps/bot/src/tf2/tf2.service.ts

When reconnecting to TF2 GC then leave all games.

fix(bot): fix custom game

---

apps/bptf-manager/src/listings/manage-listings.service.ts

Only save desired if there are any

fix: saving desired when planning listings

---

apps/bot-manager/Dockerfile
apps/bot-manager/src/bots/bots.controller.ts
apps/bot-manager/src/heartbeats/heartbeats.controller.ts
apps/bot-manager/src/inventories/inventories.service.ts
apps/bot-manager/src/main.ts
apps/bot-manager/src/trades/processors/trades.processor.ts
apps/bot-manager/src/trades/trades.controller.ts
apps/bot-manager/src/trades/trades.service.ts
apps/bot/Dockerfile
apps/bot/src/bot/bot.service.ts
apps/bot/src/main.ts
apps/bot/src/profile/profile.service.ts
apps/bot/src/tf2/tf2.service.ts
apps/bot/src/trades/trades.module.ts
apps/bptf-manager/Dockerfile
apps/bptf-manager/src/agents/agents.service.ts
apps/bptf-manager/src/inventories/inventories.service.ts
apps/bptf-manager/src/listings/classes/add-desired-listing.class.ts
apps/bptf-manager/src/listings/classes/desired-listing.class.ts
apps/bptf-manager/src/listings/classes/listing.factory.ts
apps/bptf-manager/src/listings/current-listings.service.ts
apps/bptf-manager/src/listings/listeners/desired-listings.listener.spec.ts
apps/bptf-manager/src/listings/listings.controller.ts
apps/bptf-manager/src/listings/utils/desired-listing-hash.ts
apps/bptf-manager/src/main.ts
apps/message-relay/Dockerfile
apps/message-relay/src/events/events.service.ts

Remove duplicate imports and stuff like that

refactor: fix things

---

apps/bot/README.md

chore(bot): add api key to env var table

---

apps/bot/src/main.ts

No changes are made other than attempting to retrigger the release pipeline.

fix(bot): release pipeline failed

---

apps/bot/src/bot/bot.service.ts
apps/bot/src/health/bot.health.ts

feat(bot): add reason to health checks

---

apps/bot/src/bot/bot.service.ts

Should fix the problem in #349 and adds extra debug logging to get information about the web session.

feat(bot): log web session

---

apps/bot-manager/src/trades/interfaces/trade-queue.interface.ts
apps/bot-manager/src/trades/processors/trades.processor.ts
apps/bot-manager/src/trades/trades.controller.ts
apps/bot-manager/src/trades/trades.service.ts
apps/bot/src/trades/trades.controller.ts
apps/bot/src/trades/trades.service.ts
libs/bot-data/src/lib/trades.ts
libs/bot-manager-data/src/lib/trades.ts
libs/dto/src/lib/trades.ts

Refresh trades

---

apps/bot/src/bot/bot.controller.ts
apps/bot/src/bot/bot.service.ts
libs/bot-data/src/lib/bot.ts

Get the websession cookies
Fix #356

feat(bot): add websession api

---

apps/bot/src/bot/bot.service.ts
libs/bot-data/src/lib/steam.ts

feat(bot): publish account limitations

---

.releaserc.js
package.json

Thought using semantic release v21 would fix rate limiting

fix: retrigger release

---

apps/bot/src/bot/bot.service.ts
apps/bot/src/common/config/configuration.ts
apps/bot/src/common/config/validation.ts

Move web session checks out of ready check into seperate interval

feat(bot): add web session check

---

apps/bot/src/trades/trades.service.ts

Refresh session when the error is caught while accepting, declining, canceling and sending offers.

fix(bot): refresh session on "HTTP error 500" error message

---

.github/workflows/ci.yml

ci: add e2e test job

---

apps/bot-manager/src/common/config/configuration.ts
apps/bot-manager/src/common/config/validation.ts
apps/bot-manager/src/relay/relay.service.ts

Also increases default leader election timeouts

feat(bot-manager): configure leader timeouts

---

examples/rabbitmq/receiver.ts

https://discord.com/channels/445215464386330644/1270371703561781381

chore: fix rabbitmq example

---

apps/bot-manager/src/common/config/configuration.ts
apps/bot-manager/src/main.ts
apps/bot/src/common/config/configuration.ts
apps/bot/src/main.ts
apps/bptf-manager/src/common/config/configuration.ts
apps/bptf-manager/src/main.ts

feat: keep alive timeout settings

---

libs/config/src/events.ts

If `EVENTS_TYPE` was missing, then no validation would take place.

fix(config): require rabbitmq env vars when missing events type env var

---

apps/bot-manager/src/heartbeats/heartbeats.service.ts
apps/bot-manager/src/inventories/inventories.service.ts
apps/bptf-manager/src/agents/agents.service.ts
apps/bptf-manager/src/inventories/inventories.service.ts
apps/bptf-manager/src/listings/classes/desired-listing.class.ts
apps/bptf-manager/src/listings/current-listings.service.ts
apps/bptf-manager/src/listings/desired-listings.service.spec.ts
apps/bptf-manager/src/listings/desired-listings.service.ts
apps/bptf-manager/src/listings/listeners/desired-listings.listener.spec.ts
apps/bptf-manager/src/notifications/notifications.service.ts
package.json
pnpm-lock.yaml

Data is now stored as message pack buffers instead of json strings to increase encoding and decoding performance
BREAKING CHANGE: All existing data stored in redis has to be removed to ensure that no unexpected errors will happen when decoding

perf: replace json data encoding and decoding with message pack

---

libs/tf2-format/src/lib/parsing/econ/parser.spec.ts
libs/tf2-format/src/lib/parsing/econ/parser.ts
libs/tf2-format/src/lib/parsing/econ/test-data.ts

Red Rock Roscoe Pistol does not have a checkmark or star to highlight the texture of the item
Fix #618

fix(tf2-format): handle edge case with skins

---

apps/bot-manager/src/inventories/inventories.service.ts
apps/item-service/src/inventories/inventories.service.ts

Conditionally set the expiration of inventories.
Fix #637

fix: fix problem with -1 ttl

---

apps/bot-manager/src/inventories/inventories.service.ts
apps/item-service/src/inventories/inventories.service.ts

Reverts tf2-automatic/tf2-automatic#638

Revert "fix: fix problem with -1 ttl"

---

.github/workflows/ci.yml
.github/workflows/release.yml
.husky/pre-commit
package.json
scripts/nx.js

"Proxy" nx commands and add parallel argument if not already specified.

chore: set max number of parallel processes on nx commands

---

apps/item-service/src/inventories/inventories.service.ts
apps/item-service/src/schema/schema.controller.ts
apps/item-service/src/schema/schema.service.ts
apps/item-service/src/schema/schema.types.ts
libs/item-service-data/src/lib/schema/misc.ts
libs/item-service-data/src/lib/schema/schema.ts
libs/tf2-format/src/lib/parsing/bptf/parser.spec.ts
libs/tf2-format/src/lib/parsing/bptf/parser.ts
libs/tf2-format/src/lib/parsing/helpers.ts
libs/tf2-format/src/lib/parsing/tf2/parser.spec.ts
libs/tf2-format/src/lib/parsing/tf2/parser.ts
libs/tf2-format/src/lib/parsing/tf2/types.ts
libs/tf2-format/src/lib/schemas.ts
libs/tf2-format/src/lib/types.ts

Spells are now stored as a list [defindex, value] to better identify them.
BREAKING CHANGE: Spells are handled differently by item-service and tf2-format.

feat: properly handle spells

---

apps/item-service/src/inventories/inventories.service.ts
libs/item-service-data/src/lib/inventories/index.ts
libs/tf2-format/package.json
libs/tf2-format/src/index.ts
libs/tf2-format/src/lib/binary/binary.spec.ts
libs/tf2-format/src/lib/binary/binary.ts
libs/tf2-format/src/lib/binary/index.ts
libs/tf2-format/src/lib/naming/index.ts
libs/tf2-format/src/lib/naming/naming.spec.ts
libs/tf2-format/src/lib/parsing/econ/parser.spec.ts
libs/tf2-format/src/lib/parsing/econ/parser.ts
libs/tf2-format/src/lib/parsing/econ/test-data.ts
libs/tf2-format/src/lib/sku/sku.spec.ts
libs/tf2-format/src/lib/sku/sku.ts
libs/tf2-format/src/lib/types.ts
libs/tf2-format/src/lib/utils/index.ts
libs/tf2-format/src/lib/utils/utils.spec.ts
libs/tf2-format/src/lib/utils/utils.ts
package.json
pnpm-lock.yaml

- Added util methods for working with the common format
- Handle negative defindex and quality in SKUs
- Don't include default values in result when parsing a SKU

feat(tf2-format): add binary format
